### ISSUE TITLE
Issues with libswiftCore.dylib

### ISSUE THREAD

**Issue by follesoe** [Flash3001/iOSCharts.Xamarin#17]
Recently we've started experiencing bugs when deploying to device. It works once if I do Clean on the Solution, but second build fails again with this error:

```
Launched application 'no.blueye.blueye-app' on 'iPhone' with pid 2158
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/D0FAB285-6DF9-4D95-9265-0E44F4B12036/Blueye.App.iOS.app/Frameworks/Charts.framework/Charts
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/D0FAB285-6DF9-4D95-9265-0E44F4B12036/Blueye.App.iOS.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/containers/Bundle/Application/D0FAB285-6DF9-4D95-9265-0E44F4B12036/Blueye.App.iOS.app/Frameworks/libswiftCore.dylib'

Application 'no.blueye.blueye-app' terminated.
```

Any suggestions would be greatly appreciated.

**Comment by Flash3001** [comment]
@follesoe what's your setup? Xamarin Studio or VS, which version? And what is your configuration to build/deploy: incremental? 

I need to know it so I can try to simulate the error. Everything is getting updated, maybe something broke the script, need to check.

**Comment by follesoe** [comment]
Developing on Xamarin Studio 6.2 (build 1829), incremental builds enabled.

I really appreciate you looking into this so quickly. Have a big demo coming up next week, and have been testing mostly in Simulator, so this caught me off guard).

Tried to turn off incremental builds. Only thing that works is cleaning the solution and building (and that only works once - make single change in the code and build again and the error is back).

**Comment by follesoe** [comment]
Just confirmed that the problem is easy to reproduce (on my machine at least). Created a new Single View iOS app and referenced `iOSCharts 3.0.1.1`. Create an instance of `LineChartView` in the `ViewController`. Clean the solution and debug on device. Works first time. Make a single change (like changing background color of the chart) and build. Now fails with:

```
Launched application 'no.follesoe.jonas.ioscharts3011' on 'iPhone' with pid 2802
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/21985E1A-F310-4D7B-8FC0-C7C1E785240A/ioscharts3011.app/Frameworks/Charts.framework/Charts
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/21985E1A-F310-4D7B-8FC0-C7C1E785240A/ioscharts3011.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/containers/Bundle/Application/21985E1A-F310-4D7B-8FC0-C7C1E785240A/ioscharts3011.app/Frameworks/libswiftCore.dylib'

Application 'no.follesoe.jonas.ioscharts3011' terminated.
```

Then Clean the solution and debug on device, now works again. Make a change and debug on device, and the error is back.

Good thing it is consistent. I just find it a bit strange, given the 3.0.1.1 build is from November 2016 and has ~500+ downloads. So could there have been a change in Xamarin that is making this bug occur?

**Comment by follesoe** [comment]
If I clean and build (and the app works) and I copy the Debug directory content into a folder called `Working`. Then make a change (and the app crashes) and I copy the Debug directory content into a folder called `Crashing` and diff them using: `diff -rq Working/ Crashing/` the diff is:

```
Files Working/Debug/Blueye.App.iOS.exe and Crashing/Debug/Blueye.App.iOS.exe differ
Files Working/Debug/Blueye.App.iOS.exe.mdb and Crashing/Debug/Blueye.App.iOS.exe.mdb differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/.monotouch-64/Blueye.App.iOS.arm64.aotdata and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/.monotouch-64/Blueye.App.iOS.arm64.aotdata differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/.monotouch-64/Blueye.App.iOS.exe and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/.monotouch-64/Blueye.App.iOS.exe differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/.monotouch-64/Blueye.App.iOS.exe.mdb and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/.monotouch-64/Blueye.App.iOS.exe.mdb differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/.uploaded and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/.uploaded differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Assets.car and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Assets.car differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Blueye.App.iOS and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Blueye.App.iOS differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftCore.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftCore.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftCoreAudio.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftCoreAudio.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftCoreData.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftCoreData.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftCoreGraphics.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftCoreGraphics.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftCoreImage.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftCoreImage.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftCoreMedia.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftCoreMedia.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftDarwin.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftDarwin.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftDispatch.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftDispatch.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftFoundation.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftFoundation.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftObjectiveC.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftObjectiveC.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftQuartzCore.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftQuartzCore.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftUIKit.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftUIKit.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftos.dylib and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/Frameworks/libswiftos.dylib differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/_CodeSignature/CodeResources and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app/_CodeSignature/CodeResources differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app.dSYM/Contents/Resources/DWARF/Blueye.App.iOS and Crashing/Debug/device-builds/iphone8.1-10.2.1/Blueye.App.iOS.app.dSYM/Contents/Resources/DWARF/Blueye.App.iOS differ
Files Working/Debug/device-builds/iphone8.1-10.2.1/Charts.framework.dSYM/Contents/Resources/DWARF/Charts and Crashing/Debug/device-builds/iphone8.1-10.2.1/Charts.framework.dSYM/Contents/Resources/DWARF/Charts differ
```

So; it all the Swift `*.dylib` files differ, I guess as expected. So it is like the dylib files are signed differently (or not signed at all) when I build for the second time around...

**Comment by Flash3001** [comment]
@follesoe I was able to figure it out. It is indeed a bug in Xamarin and it has already been fixed in their master branch. 

The problem is the code to sign the app bundle is being ignored by msbuild as it detects no files has changed. 

[This bug report](https://bugzilla.xamarin.com/show_bug.cgi?id=52165#c13) is similar to the problem we see in here, but it has not fixed our problem. If you take a look at the [file change](https://github.com/xamarin/xamarin-macios/pull/1612/files) in the PR the Inputs for the Task that run the CodeSign has changed (the inputs/outputs is how msbuild determines it has to run a task).
Actually this code is already available in the stable channel. 

Now, if you take a look in the master branch the [Inputs/Outputs for the CodesignAppBundle has been changed again](https://github.com/xamarin/xamarin-macios/blob/master/msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets#L1810). **If you copy the specific lines of code to the Xamarin.iOS.Common.targets in your computer it will fix the issue.** 

I can't say if it is already available in Xamarin alpha channel.

The file is located in: /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS

Before:
```
<Target Name="_CalculateCodesignAppBundleInputs" Condition="'$(_RequireCodeSigning)' == 'true'">
		<ItemGroup>
			<_CodesignAppBundleInput Include="$(_NativeExecutable)" />
			<_CodesignAppBundleInput Include="$(_AppBundlePath)Info.plist" />
			<_CodesignAppBundleInput Include="$(_AppBundlePath)embedded.mobileprovision" />
			<_CodesignAppBundleInput Include="$(DeviceSpecificIntermediateOutputPath)Entitlements.xcent" />
			<_CodesignAppBundleInput Include="@(_BundleResourceWithLogicalName)" />
			<_CodesignAppBundleInput Include="@(_NativeLibrary)" />
			<_CodesignAppBundleInput Include="@(_Frameworks)" />
			<_CodesignAppBundleInput Include="@(_ResolvedAppExtensionReferences -> '$(_AppBundlePath)PlugIns\%(FileName)%(Extension)\_CodeSignature\CodeResources')" Condition="'$(IsAppExtension)' == 'false'" />

			<!-- Include WatchOS1 App references -->
			<_CodesignAppBundleInput Include="@(_ResolvedWatchAppReferences -> '$(_AppBundlePath)%(FileName)%(Extension)\_CodeSignature\CodeResources')" Condition="'$(IsAppExtension)' == 'true'" />

			<!-- Include WatchOS2 App references -->
			<_CodesignAppBundleInput Include="@(_ResolvedWatchAppReferences -> '$(_AppBundlePath)Watch\%(FileName)%(Extension)\_CodeSignature\CodeResources')" Condition="'$(OutputType)' == 'Exe'" />
		</ItemGroup>
	</Target>

	<Target Name="_CodesignAppBundle" Condition="'$(_RequireCodeSigning)' == 'true'" DependsOnTargets="$(_CodesignAppBundleDependsOn)"
		Inputs="@(_CodesignAppBundleInput)"
		Outputs="$(DeviceSpecificIntermediateOutputPath)codesign\$(_AppBundleName)$(AppBundleExtension)">
```

After:
```
<Target Name="_CalculateCodesignAppBundleInputs" Condition="'$(_RequireCodeSigning)' == 'true'">
		<ItemGroup>
			<_CodesignAppBundleInputs Include="$(_AppBundlePath)**\*.*" Exclude="$(_AppBundlePath)_CodeSignature\CodeResources" />
		</ItemGroup>
	</Target>

	<Target Name="_CodesignAppBundle" Condition="'$(_RequireCodeSigning)' == 'true'" DependsOnTargets="$(_CodesignAppBundleDependsOn)"
		Inputs="@(_CodesignAppBundleInputs)" Outputs="$(_AppBundlePath)_CodeSignature\CodeResources">
```

Warning: Do not copy the entire file, as it will break other things.
Warning 2: You should not normally modify this file, as it is Xamarin's and can stop the build process from working if you do the wrong thing. 
Warning 3: It will be replaced when you update Xamarin.

**Comment by follesoe** [comment]
Sure that is the only change needed? I've updated my `/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets` file, made sure to only change the lines you pointed out. I've rebooted my computer just to be 100% sure the Xamarin Studio process hadn't cached it anywhere.

The symptom remains; works on first build, fails on second:

```
Launched application 'no.blueye.blueye-app' on 'iPhone' with pid 3421
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/2145F986-3124-4CE9-836A-899AD9413E0E/Blueye.App.iOS.app/Frameworks/Charts.framework/Charts
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/2145F986-3124-4CE9-836A-899AD9413E0E/Blueye.App.iOS.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/containers/Bundle/Application/2145F986-3124-4CE9-836A-899AD9413E0E/Blueye.App.iOS.app/Frameworks/libswiftCore.dylib'

Application 'no.blueye.blueye-app' terminated.
```

But I totally agree that this sounds like the problem, so we're on the right track.

**Comment by follesoe** [comment]
Switched to Beta-channel, which includes Xamarin Studio 6.3.0, but the problem still persists with same error message (`...code signature invalid for...`).

**Comment by Flash3001** [comment]
Please, enable [Diagnostic Build Logs](https://forums.xamarin.com/discussion/27515/how-to-obtain-diagnostic-build-logs) in your Xamarin and send the logs for the second build. The goal is to see the lines related to _CodesignAppBundle and _CodesignNative.

Have you done the tests in your test project as well no.follesoe.jonas.ioscharts3011 ?

**Comment by follesoe** [comment]
Tested on the `no.follesoe.jonas.ioscharts3011` app with same error.

Full diagnostics build log: [Diagnostics Build Log.txt](https://github.com/Flash3001/iOSCharts.Xamarin/files/854908/Diagnostics.Build.Log.txt)

**Comment by Flash3001** [comment]
@follesoe I'm not able to reproduce the problem anymore. 

Just to be sure, would you uninstall the app and remove the 'bin' and 'obj' folders (in the file system, not just 'clean build')? 

Your code sign check on build says: 
> 		valid on disk
> 		satisfies its Designated Requirement
> 		explicit requirement satisfied

But when running it says: 
> code signature invalid for

**Comment by follesoe** [comment]
Did a new attempt, with deleting obj and bin folder before building for device. Same result (works first time not second).

- [First Build Working.txt](https://github.com/Flash3001/iOSCharts.Xamarin/files/872380/First.Build.Working.txt)
- [Second Build Failing.txt](https://github.com/Flash3001/iOSCharts.Xamarin/files/872383/Second.Build.Failing.txt)

My patched targets file:

```xml
<Target Name="_CalculateCodesignAppBundleInputs" Condition="'$(_RequireCodeSigning)' == 'true'">
	<ItemGroup>
		<_CodesignAppBundleInputs Include="$(_AppBundlePath)**\*.*" Exclude="$(_AppBundlePath)_CodeSignature\CodeResources" />
	</ItemGroup>
</Target>

<Target Name="_CodesignAppBundle" Condition="'$(_RequireCodeSigning)' == 'true'" DependsOnTargets="$(_CodesignAppBundleDependsOn)"
	Inputs="@(_CodesignAppBundleInputs)" Outputs="$(_AppBundlePath)_CodeSignature\CodeResources">
```

**Comment by follesoe** [comment]
Also tried to completely reinstall Xamarin and create a new single view app, same problem...

**Comment by follesoe** [comment]
Tried to upgrade to the 6.3 on the Alpha channel, same issue.

Tried to log the files included in the `_CalculateCodesignAppBundleInputs` set, and all the Swift *.dylib files are included.

```
bin/iPhone/Release/chartstest.app/Frameworks/libswiftCore.dylib;
bin/iPhone/Release/chartstest.app/Frameworks/libswiftCoreAudio.dylib;
bin/iPhone/Release/chartstest.app/Frameworks/libswiftCoreData.dylib;
bin/iPhone/Release/chartstest.app/Frameworks/libswiftCoreGraphics.dylib;
bin/iPhone/Release/chartstest.app/Frameworks/libswiftCoreImage.dylib;
bin/iPhone/Release/chartstest.app/Frameworks/libswiftCoreMedia.dylib;
bin/iPhone/Release/chartstest.app/Frameworks/libswiftDarwin.dylib;
bin/iPhone/Release/chartstest.app/Frameworks/libswiftDispatch.dylib;
bin/iPhone/Release/chartstest.app/Frameworks/libswiftFoundation.dylib;
bin/iPhone/Release/chartstest.app/Frameworks/libswiftObjectiveC.dylib;
bin/iPhone/Release/chartstest.app/Frameworks/libswiftQuartzCore.dylib;
bin/iPhone/Release/chartstest.app/Frameworks/libswiftUIKit.dylib;
bin/iPhone/Release/chartstest.app/Frameworks/libswiftos.dylib;
```

The `_CodesignVerify` task do verify the bundle...

```
bin/iPhone/Release/chartstest.app: valid on disk
bin/iPhone/Release/chartstest.app: satisfies its Designated Requirement
bin/iPhone/Release/chartstest.app: explicit requirement satisfied
```

**Comment by follesoe** [comment]
According to http://stackoverflow.com/documentation/xamarin.ios/6091/binding-swift-libraries/21236/6-include-all-swift-dependencies-to-run#t=201703161157301692748 you need to include the Swift libraries in the IPA package. Is that still the case?

I'm using Visual Studio Team System to create the IPA package, and publish it to HockeyApp. Do I need to manually do the step using the script found at https://github.com/bq/ipa-packager - or is this only for app store submission (not ad-hock builds distributed using HockeyApp)?

I was willing to accept having to clean before build when testing locally on device, but now I'm having issues with my CI builds as well (which are doing clean builds every time) - so it might be a different problem relating to the IPA file?

**Comment by follesoe** [comment]
Tried to verify the signed .app file inside the IPA file; getting the following error:

```
$ codesign --verify --verbose ~/Downloads/Payload/Blueye.App.iOS.app
/Users/follesoe/Downloads/Payload/Blueye.App.iOS.app: a sealed resource is missing or invalid
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftCoreGraphics.dylib
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftFoundation.dylib
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftDispatch.dylib
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftObjectiveC.dylib
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftDarwin.dylib
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftCoreAudio.dylib
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftos.dylib
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftCore.dylib
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftCoreData.dylib
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftCoreImage.dylib
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftQuartzCore.dylib
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftCoreMedia.dylib
file missing: /Users/follesoe/Downloads/Payload/Blueye.App.iOS.app/SwiftFrameworksSimulator/libswiftUIKit.dylib
```

Looks like the app is signed before the `SwiftFrameworksSimulator` folder is deleted by the `_RemoveExtraLibs` target?

**Comment by Flash3001** [comment]
@follesoe This issue related to the files in SwiftFrameworksSimulator being removed after the app being signed was fixed and an updated released yesterday. Just update this library https://www.nuget.org/packages/Xamarin.Swift3/3.0.1

You can check the change in here https://github.com/Flash3001/Xamarin.Swift3.Support/commit/eb46f5d68a7e730e51ff6aa74b441cf3fa5e3160

Regarding generating the IPA using VSTS and running the script: I've seen some people state they were able to send the app to the App Store without running this script, but I can't verify that, as I always need to do it.

The problem applies to the App Store and TestFlight, as Apple needs to validate your binary on the server in both cases. Actually, the process to send the binary is the same for both. After the binary is available on Connect you chose to send it to TestFligh or Publish (at this point they validate the app itself, not the binaries). 

Here what usually happens:

- You create the IPA without the SwiftSupport folder.
- Send it using Application Loader
- Application Loader tells you it's all OK.
- You wait 1 to 2 hours until Apple sends you an e-mail saying the app binary is invalid as it doesn't provide the SwiftSupport folder.

Something like this e-mail fragment: 

> Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

I believe you do not need to run the script manually, you could modify your build script to either

1. Extract the IPA after it is created and run the script.
2. Stop the build from creating the IPA and run the script directly in the .APP file inside the bin folder.

If you need an example on how to run the script:

`sh package_ipa.sh /Users/flash/Desktop/SuasVendas/Payload/SuasVendasIOS.app /Users/flash/Desktop/SuasVendas/YS.Mobile.iOS.ipa`
 
An important note: Your Xcode version must be compatible with the version of the NuGet packages you are using. Yesterday Apple updated Xcode to 8.3 and it came with Swift 3.1, so I needed to update all libraries to use this new version. 
https://www.nuget.org/packages/Xamarin.Swift3.Core/3.1.0

When it was Xcode 8.2 Swift's version was 3.0.2 so you should be using version https://www.nuget.org/packages/Xamarin.Swift3.Core/3.0.2

**Comment by follesoe** [comment]
Thanks for the thorough reply. Updating the packages to `3.1.0`solved the `SwiftFrameworksSimulator` issues, and my build server can now push to HockeyApp.

As for adding the swift folders for the IPA before submitting to TestFlight (when I get that far) I'll go for your option 2 - extract the IPA, run the script, and then upload the artifact. I tried the script locally and it worked fine, and it's easy to add custom shell steps to the VSTS build process so that shouldn't be an issue. As for my local device builds I can live with having to clean, and hope this will be resorted in a future Xamarin release. At least I can now continue pushing new builds to my testers, which is most important at this stage.

**Comment by follesoe** [comment]
Sorry for bringing this issue back to life - and I'm not sure if this is a new issue or related. We're now seeing this issue (in simulator) using iOS 10.3 and latest Xamarin Studio (6.2.1)

```
dyld: lazy symbol binding failed: Symbol not found: __TTSfq4n_s___TFVSS13CharacterView38_measureExtendedGraphemeClusterForwardfT4fromVVSS17UnicodeScalarView5Index_Si
  Referenced from: /Users/follesoe/Library/Developer/CoreSimulator/Devices/BE265A22-92D5-4322-B12B-08CD8533D529/data/Containers/Bundle/Application/8F9D252A-1FCF-481E-99E8-82A2B5B6C475/Blueye.App.iOS.app/Frameworks/Charts.framework/Charts
  Expected in: /Users/follesoe/Library/Developer/CoreSimulator/Devices/BE265A22-92D5-4322-B12B-08CD8533D529/data/Containers/Bundle/Application/8F9D252A-1FCF-481E-99E8-82A2B5B6C475/Blueye.App.iOS.app/Frameworks/libswiftCore.dylib

dyld: Symbol not found: __TTSfq4n_s___TFVSS13CharacterView38_measureExtendedGraphemeClusterForwardfT4fromVVSS17UnicodeScalarView5Index_Si
  Referenced from: /Users/follesoe/Library/Developer/CoreSimulator/Devices/BE265A22-92D5-4322-B12B-08CD8533D529/data/Containers/Bundle/Application/8F9D252A-1FCF-481E-99E8-82A2B5B6C475/Blueye.App.iOS.app/Frameworks/Charts.framework/Charts
  Expected in: /Users/follesoe/Library/Developer/CoreSimulator/Devices/BE265A22-92D5-4322-B12B-08CD8533D529/data/Containers/Bundle/Application/8F9D252A-1FCF-481E-99E8-82A2B5B6C475/Blueye.App.iOS.app/Frameworks/libswiftCore.dylib
```

**Comment by Flash3001** [comment]
@follesoe I believe it is a new issue. Please create a new one. 

Did you update to the new package https://www.nuget.org/packages/Xamarin.Swift3.Core/ and related?

**Comment by flashfoxter** [comment]
Hi, please help i have same issues.

Launched application 'com.x.x’ on ‘x’s iPad' with pid 233
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/EEF1ADBE-7D7A-Application 'com.x.x' terminated.
4A11-9693-1A594AF4495C/x.iOS.app/Frameworks/Charts.framework/Charts
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/EEF1ADBE-7D7A-4A11-9693-1A594AF4495C/x.iOS.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/containers/Bundle/Application/EEF1ADBE-7D7A-4A11-9693-1A594AF4495C/x.iOS.app/Frameworks/libswiftCore.dylib'

Xamarin Studio Community 6.3 (build 863)
Stable channel 
Xcode Version 8.3.2 (8E2002)

**Comment by moamen-naanou** [comment]
Hi, I have similar issue with different swift library `libswiftCoreFoundation.dylib`.

packages.config file:
```
<packages>
  <package id="Xamarin.Swift4" version="4.0.0.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Swift4.CoreFoundation" version="4.0.3" targetFramework="xamarinios10" />
</packages>
```

Error:

```
dyld: Library not loaded: @rpath/libswiftCoreFoundation.dylib
  Referenced from: /private/var/containers/Bundle/Application/47AA1F21-E2A5-4CA2-B5DB-3182127D38AC/MyApp.app/Frameworks/EmiratesIDFw.framework/EmiratesIDFw
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/47AA1F21-E2A5-4CA2-B5DB-3182127D38AC/MyApp.app/Frameworks/libswiftCoreFoundation.dylib: code signature invalid for '/private/var/containers/Bundle/Application/47AA1F21-E2A5-4CA2-B5DB-3182127D38AC/MyApp.app/Frameworks/libswiftCoreFoundation.dylib'
	/private/var/containers/Bundle/Application/47AA1F21-E2A5-4CA2-B5DB-3182127D38AC/MyApp.app/Frameworks/libswiftCoreFoundation.dylib: stat() failed with errno=1
	/private/var/containers/Bundle/Application/47AA1F21-E2A5-4CA2-B5DB-3182127D38AC/MyApp.app/Frameworks/libswiftCoreFoundation.dylib: code signature invalid for '/private/var/containers/Bundle/Application/47AA1F21-E2A5-4CA2-B5DB-3182127D38AC/MyApp.app/Frameworks/libswiftCoreFoundation.dylib'
Application 'com.MyApp' terminated.
```

Can anyone help please?
